#index:
#    path: /
#    controller: App\Controller\DefaultController::index
access_denied:
   path: /admin/erreur-403 
   controller: App\Controller\ErrorController::error403
   
page_not_found:
    path:  /{path}
    defaults: { _controller: App\Controller\ErrorController:error404, path: '' }
    requirements:
       path: .*

