# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    evenement_directory: '%kernel.project_dir%/public/uploads/Evenements'
    articles_directory: '%kernel.project_dir%/public/uploads/article'
    products_directory: '%kernel.project_dir%/public/uploads/products'
    twilio_account_sid: '%env(TWILIO_ACCOUNT_SID)%'
    twilio_auth_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio_phone_number: '+12765337052'

    from_email: '%env(FROM_EMAIL)%'
    lws: '%env(LWS)%'
    password : '%env(PASS)%'

services:
    
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $accountSid: '%env(TWILIO_ACCOUNT_SID)%'
            $authToken: '%env(TWILIO_AUTH_TOKEN)%'

    App\Controller\MyController:
        arguments:
            $twilioService: '@App\Service\TwilioService'

    App\Service\TwilioService:
        arguments:
            $accountSid: '%env(TWILIO_ACCOUNT_SID)%'
            $authToken: '%env(TWILIO_AUTH_TOKEN)%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Controller\DefaultController:
        autowire: true
   
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
